### ISSUE TITLE
Support for LZMA-compressed asset

### ISSUE THREAD

**Issue by sikachu** [Ishotihadus/mikunyan#1]
Hello,

First of all, thank you for this amazing tool. This project allows me to play with Unity3D asset in the programming language that I enjoy writing the most.

I'm currently trying to use mikunyan to unpack some assets from another Unity-based game. I've tested their asset bundle format and found out that `flags & 0x3f` for the data is `1`, which is supposed to be LZMA format, which is currently unsupported based on this comment:

https://github.com/Ishotihadus/mikunyan/blob/5c32fc9b8c3c75e726fe72dda2f9bf450bad58a7/lib/mikunyan/asset_bundle.rb#L120-L121

I was trying to implement the support myself using `extlzma` that's being used in this project. However, it seems like no matter how I tried I can't make LZMA recognize the binary string as LZMA format.

I was looking around to see how other projects are doing and seems like [AssetStudio](https://github.com/Perfare/AssetStudio/blob/cffe96b409943e04d2ad6ebd2624943f59ba91a4/AssetStudio/BundleFile.cs#L201) uses a `SevenZipHelper` which is not available in Ruby, but [UnityPack](https://github.com/HearthSim/UnityPack/blob/b936bfd0271c0e4b5347b1d0969ce599a269b6c4/unitypack/assetbundle.py#L165-L176) seems to be using liblzma which means it should be possible for us to do the same ... but I really can't wrap my head around how they able to make it work, given many of the documentation are in Japanese.

Since I'm pretty much banging my head against the wall now, I wonder if you'll be able to take a look on what am I missing to make this work?

The example asset that I'm trying to extract is this: https://mega.nz/#!UoA3CKYT!nTeOyfoDOzRk7Ee6wfgj9YNlHwNooe2lO3vWbuwWp_I

Thank you very much.

**Comment by Ishotihadus** [comment]
I was working on it and I just implemented. I will release the new version in a few days.
Thank you for your contribution.

**Comment by sikachu** [comment]
I just read your code in e1ac05e540061c497e56cb9d8dc91fbc8c7ca82b and realized what I missed. Working with binary surely is hard. 😖

Thank you for your work, and I'll look forward to the next release. 🙇‍♂️

**Comment by Ishotihadus** [comment]
I released v3.9.7, which supports assetbundles compressed in LZMA.
